apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-keys
  namespace: urlshortener
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    public-key: AgBrKbtTRN/dwNLNZnbtHKYT5RvKXoO3fzKy+eR4u7xPBKEn4DbPbOvW31mL2OSZBqHsM569urKbCsvxOdg+15ZZQnVqeQBwHb29o8syGaHbVWKjxwajYCXmB/tLZT1zlXAJaRwxyx/Zbs/IxRAucalCBnRqcUZmOEHQWiPfsXd/Oah/Iy1YDATsVMhp2tMHDDuUJJlHoM2CS/9jnCD2sMguqIAfx5Ixt3bEqOXie9YVEl7AI5Ki81mGjm1Atg73+3D6BI9IxKS63SHdRuifPJgubv41ART8wllR2uopps3oWiVzQkyo2HLpndNDHv+jH/rOM2oEAdr122dIINTK3I1HDmv0IwJIi0TptFXH5+eh1Swn+gJbJ9XBByjNiooTlG896RViIZdy00C8eowvyTg+X4AtnX/isCB2eANyc1zwzCEHiqxSycccsLQGLS9K6FO2Ju+Nk7ExROraLV3CUpOT4lAe+c/e+vwLd8t0Jycfgq94bnwnbnjxt0qMAJ9PGd/7n4DDJYELphDTtm8U5IKgifSzUcyBhaERQmUQEMdQ3zLwDfMyIW/lDPMW1HMFmfOx497vLuAn7heK4KuClPx3bY6+LJIhHjJjmpmGFdO31346gPVp6TILKwrVzg4YHLc+Qed/meIPbbfIyXItLKzB5emquXNyN+9hQZcDL8dczdiNaM0TAtoR38D4EkTrsIC5ZYcuu+y+FgudV8Lzc6RRVnPIYlGL8lgSM1u4FBm2veoof9GXQ9hDw/2BXRo2Qj0yq1jfQ1FZX2yCw6R3aJmjWeltT9wETsCvPrD2wYKBce4/MNVMTeoTt8vxqx0S8Ul3+zOWHfTdk0yKS35JPfYbPfSy4Ko6J+uwKlSt1f8Bd+vD4zjpg0foqC755u7tT9ZvIoxyMiHwvrgOWM2LQGpSRtGeBovRYdprED91Csfr+CgUT9YT70jTfKYjk3cdoOjMCLTRAmrb8wECdVNx7XFjDDml3dkiS+FulDk+CUe97DuPXoJ+pQLP+pJt/9nlnXyVT0uHMjyxYm36Br3smjpR6rB22P1qmxNqHqQ9iDZDGt/j7TNdhweHZWuw7dze5Oc48WdyK5DCkDT53wYHcqHhBxl2PouXoiC369/K+QWvQRs/NYDZJxgyPhYXh9Pjm90lNBNA09/7QBh47fFnxunVuLcHPHqLj9A2JumTesB3AKkPU8av8tlHYcYh7M3WNw2pHXENxwgnu5qk0xPAh89StZu2xGbejQ9EHfvJzA1vNqzK2V0GMxpz5r3ZKKFWxR41C9j5PulWBh/0dyJUsqHSBqA=
  template:
    metadata:
      name: jwt-keys
      namespace: urlshortener
    type: Opaque
