apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: urlshortener
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    addr: AgCOPbPoXjYTpBj1tFUe23RYmCNPWIE7iKfXhZDT9nO6QJLekiAT2VXEi/t3tV/9c5edNRvANNpR6mNxWakuWrJB62/6sNjYYH8fQRUHreQehTt1vXZ4rauHWUMtkYU5ddiEYQhm8ne/rj+a6bTKqfqEu6T9fVNDwy/oQmIC0X7AFcdB8mVWfAXKrvPdrqNcgqFRLL7IXpuzYsfo9rqIqv4oUwRGekSxyHAMqsYrYFK9XHgMBPO8gsETBpdiRXk8k4dEah+y1fx6Q7ns6YGVKnkeoAa03croD/72Q9qCeoWaFxvntRLaLw20yhCCVQ4WIyS6kS4aleHUBjt1jkkTx61HyZxuPk1nIxQlR7dPfaIrJCo3+CI1HHDrnwQNsPrWd5WzrzTHMRYPV4kdN9MgnCs+71gPzPAM1M+kvO/zlQ1L+gAmq1xyhUHJlQH+9ldMGAqSxFWAvSjbSi0OhoUMVenVW7zuT0yASEs8ASmmMoSXpnOo7moRZPdkQxTWn1J/gHQrRSTxcFcmrdBqLv57rxBJ4VB4wzS7DEXvO43WgSyrbrX4P0tkirh+EGAc3MIXUsrYmbbCEfuUqIlBi7WuK3sFe108nXpJwmKpSfcfp5NXSsx9g6kJ9a2UvpVscYWgCIIjyQ5ZVd8TYQRFPcwmRFVISz6V39bOIvFn+Bv0MshEucFBmJp3Y2rWaHdT9+JQXmoN1Hhb+Zq207EMUZETxA==
    password: AgB7H8sX8v8slTPy709oZnnpm6B1TQlrOEceqnWAHLpM9u1Qco62BuL1wGKDKWfPXwNFQ9CXXzRSIStd2rM3XpvQnoJJRXtwgr3kbKCYl9dWdXfymvRJR0JSy7MQ1zWBhThuACIJec07L4xr2HuoqXSznROiyhiSTx4L9Y4m9f3ur13L6E7K6FJ/1xEiYT0rdtdeoYu0JY/L6CKBU6BR9Gj0mWhHchvfZU03v/REQB+cFPlDP+Y98tH1k9p3t90UBIyRAqXgP3ASjOkdbc65nDGImxCQldbqGAv07n8ijlTHe8KB7k/KThrSvkGhas3Lc30rBfvLbo+WYtKVg7rFyEjR3bG78eJQ3tu/tv3l/WkCnnccNAKztYmsVYvmWaK5AfpyFM8jOoYIu99G2W2+rla3zAdqo7ukzCJ9d2GE2/yEwf7hjdLyGkKV87aLDWTN2SIy/PFUfTWhBBZTLSIxf2vUf2zoxRpfUg+8Xug1HRlulTLtDpyz5FJ+mLbsn1lWLiSSjpjVhRMhMtdKEPiq4WNbEJmsC9M50GbzV13HrQnpfLYACu4g+ufLDb4OHdL/FNMk9pUZ62e7HCz848XCPRZ5U1S5mp7BAvN32iNZ6uj2skOIWizGjMH6QHu8i6i/cqPxHx85LMEb+XHGbIP9qoHUaE95jWv1XZ7E2D2bNIe3SJfU/bFRIdwtPJhb4WHy49p2RiNoOxQ=
  template:
    metadata:
      name: redis-credentials
      namespace: urlshortener
    type: Opaque
