apiVersion: v1
kind: Secret
metadata:
  name: urlshortener-secrets
  namespace: urlshortener
type: Opaque
stringData:
  POSTGRES_USER: urlshortener
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: urlshortener
  REDIS_PASSWORD: secret
  DB_PRIMARY_DSN: postgresql://urlshortener:secret@postgres.urlshortener.svc.cluster.local:5432/urlshortener?sslmode=disable
  DB_REPLICA_DSN: postgresql://urlshortener:secret@postgres.urlshortener.svc.cluster.local:5432/urlshortener?sslmode=disable
  EXPORT_SIGN_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  IP_HASH_SALT: local-dev-salt-change-me
