apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redirector-pdb
  namespace: urlshortener
  labels:
    app: redirector
    component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: redirector
