apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: urlshortener
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - urlshortener
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
